### ISSUE TITLE
Error when saving updates

### ISSUE THREAD

**Issue by annakijas1** [BCLibraries/softwaretracker#2]
When attempting to update an entry an error message pops up. See screenshot.

<img width="743" alt="screen shot 2017-12-13 at 10 40 12 am" src="https://user-images.githubusercontent.com/6841932/33947303-087a44e6-dff2-11e7-95a0-40b04ffaa49d.png">

**Comment by bc-raymc** [comment]
During the last update an attribute was mangled and that prevented the update script from running. The attribute has been fixed.
